#pragma once

// KODY KLAWISZY
#define SPACJA 32
#define STRZALKA -32
#define STRZALKA_GORA 72
#define STRZALKA_DOL 80
#define STRZALKA_PRAWO 77
#define STRZALKA_LEWO 75

// KLAWISZE
#define WYJSCIE_Z_GRY 'q'
#define NOWA_GRA 'n'
#define ZDOLNOSC 'z'
#define ZAPISZ 's'
#define WCZYTAJ 'l'

// POLOZENIE ELEMENTOW
#define X_MAPY 70
#define Y_MAPY 5

#define X_INFORMACJE 1
#define Y_INFORMACJE 3

#define X_KOMUNIKATY 0
#define Y_KOMUNIKATY (Y_MAPY + 22)

#define X_AUTOR 0
#define Y_AUTOR 0

// KOMUNIKATY
#define LIMIT_KOMUNIKATOW 10

// RYSOWANIE PLANSZY
#define PUSTE_POLE '.'
#define RAMKA '#'

// WYPELNIANIE PLANSZY
#define SZANSA_ZAJECIA_POLA 0.15
#define LICZBA_TYPOW_ORGANIZMOW 11

// -----------
//  ORGANIZMY
// -----------

// ANTYLOPA
#define TYP_ANTYLOPA				"Antylopa"
#define SILA_ANTYLOPA				4
#define INICJATYWA_ANTYLOPA			4
#define OZNACZENIE_ANTYLOPA			'A'
#define SZANSA_RUCHU_ANTYLOPA		1.00
#define ZASIEG_RUCHU_ANTYLOPA		2
#define SZANSA_UCIECZKI_ANTYLOPA	0.50
#define SZANSA_ROZMNAZANIA_ANTYLOPA	1.00

// BARSZCZ SOSNOWSKIEGO
#define TYP_BARSZCZ					"Barszcz_Sosnowskiego"
#define SILA_BARSZCZ				10
#define INICJATYWA_BARSZCZ			0
#define OZNACZENIE_BARSZCZ			'B'	
#define PROBY_ROZMNAZANIA_BARSZCZ	1
#define SZANSA_ROZMNAZANIA_BARSZCZ	0.08

// GUARANA
#define TYP_GUARANA					"Guarana"
#define SILA_GUARANA				0
#define INICJATYWA_GUARANA			0
#define OZNACZENIE_GUARANA			'G'	
#define PROBY_ROZMNAZANIA_GUARANA	1
#define SZANSA_ROZMNAZANIA_GUARANA	0.08

// LIS
#define TYP_LIS						"Lis"
#define SILA_LIS					3
#define INICJATYWA_LIS				7
#define OZNACZENIE_LIS				'L'
#define SZANSA_RUCHU_LIS			1.00
#define ZASIEG_RUCHU_LIS			1
#define SZANSA_UCIECZKI_LIS			0.00
#define SZANSA_ROZMNAZANIA_LIS		1.00

// MLECZ
#define TYP_MLECZ					"Mlecz"
#define SILA_MLECZ					0
#define INICJATYWA_MLECZ			0
#define OZNACZENIE_MLECZ			'M'	
#define PROBY_ROZMNAZANIA_MLECZ		3
#define SZANSA_ROZMNAZANIA_MLECZ	0.08

// OWCA
#define TYP_OWCA					"Owca"
#define SILA_OWCA					4
#define INICJATYWA_OWCA				4
#define OZNACZENIE_OWCA				'O'
#define SZANSA_RUCHU_OWCA			1.00
#define ZASIEG_RUCHU_OWCA			1
#define SZANSA_UCIECZKI_OWCA		0.00
#define SZANSA_ROZMNAZANIA_OWCA		1.00

// TRAWA
#define TYP_TRAWA					"Trawa"
#define SILA_TRAWA					0
#define INICJATYWA_TRAWA			0
#define OZNACZENIE_TRAWA			'T'	
#define PROBY_ROZMNAZANIA_TRAWA		1
#define SZANSA_ROZMNAZANIA_TRAWA	0.08

// WILCZE JAGODY
#define TYP_JAGODY					"Wilcze_Jagody"
#define SILA_JAGODY					99
#define INICJATYWA_JAGODY			0
#define OZNACZENIE_JAGODY			'J'	
#define PROBY_ROZMNAZANIA_JAGODY	1
#define SZANSA_ROZMNAZANIA_JAGODY	0.08

// WILK
#define TYP_WILK					"Wilk"
#define SILA_WILK					9
#define INICJATYWA_WILK				5
#define OZNACZENIE_WILK				'W'
#define SZANSA_RUCHU_WILK			1.00
#define ZASIEG_RUCHU_WILK			1
#define SZANSA_UCIECZKI_WILK		0.00
#define SZANSA_ROZMNAZANIA_WILK		1.00

// ZOLW
#define TYP_ZOLW					"Zolw"
#define SILA_ZOLW					2
#define INICJATYWA_ZOLW				1
#define OZNACZENIE_ZOLW				'Z'
#define SZANSA_RUCHU_ZOLW			1.00
#define ZASIEG_RUCHU_ZOLW			1
#define SZANSA_UCIECZKI_ZOLW		0.00
#define SZANSA_ROZMNAZANIA_ZOLW		1.00

// CZLOWIEK
#define TYP_CZLOWIEK				"Czlowiek"
#define SILA_CZLOWIEK				5
#define INICJATYWA_CZLOWIEK			4
#define OZNACZENIE_CZLOWIEK			'@'
#define SZANSA_RUCHU_CZLOWIEK		1.00
#define ZASIEG_RUCHU_CZLOWIEK		1
#define SZANSA_UCIECZKI_CZLOWIEK	0.00
#define SZANSA_ROZMNAZANIA_CZLOWIEK	0.00
#define MAX_TRWANIE_ZDOLNOSCI		5
#define MAX_ODNOWIENIE_ZDOLNOSCI	5